DATA PREPROCESSING AND FEATURE ENGINEERING IN MACHINE LEARNING

Objective:
This assignment aims to equip you with practical skills in data preprocessing, feature engineering, and feature selection techniques, which are crucial for building efficient machine learning models. You will work with a provided dataset to apply various techniques such as scaling, encoding, and feature selection methods including isolation forest and PPS score analysis.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Loading the dataset
df = pd.read_csv("adult_with_headers_(1).csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [7]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [41]:
df.tail()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [8]:
df.shape

(32561, 15)

In [9]:
df.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [5]:
# Check missing values
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [6]:
# identifying categorical columns
categorical_cols=df.select_dtypes(include=['object']).columns
categorical_cols

Index(['workclass', 'education', 'marital_status', 'occupation',
       'relationship', 'race', 'sex', 'native_country', 'income'],
      dtype='object')

In [7]:
# Checking for missing values '?'in categorical columns
(df[categorical_cols] == ' ?').sum()

workclass         1836
education            0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
native_country     583
income               0
dtype: int64

In [8]:
# percentage of missing values
missing_summary = pd.DataFrame({
    'Missing_Count': (df[categorical_cols] == ' ?').sum(),
    'Missing_Percentage': (df[categorical_cols] == ' ?').mean() * 100
})
missing_summary

                Missing_Count  Missing_Percentage
workclass                1836            5.638647
education                   0            0.000000
marital_status              0            0.000000
occupation               1843            5.660146
relationship                0            0.000000
race                        0            0.000000
sex                         0            0.000000
native_country            583            1.790486
income                      0            0.000000

In [9]:
# Replace '?' with NaN
df.replace(" ?", np.nan, inplace=True)

In [10]:
#Impute Categorical Columns with Mode
for col in df.select_dtypes(include="object").columns:
    df[col].fillna(df[col].mode()[0], inplace=True) # [0] selects the first most frequent value

In [11]:
# Checking for missing values replaced
(df[categorical_cols] == ' ?').sum()

workclass         0
education         0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
native_country    0
income            0
dtype: int64

●	Apply scaling techniques to numerical features:
a.	Standard Scaling   b. Min-Max Scaling

In [12]:
# selecting numerical columns
num_features = df.select_dtypes(include=["int64", "float64"]).columns

In [13]:
# a. Standard Scaling
from sklearn.preprocessing import StandardScaler

In [14]:
std_scaler = StandardScaler()
df_std_scaled = df.copy()
df_std_scaled[num_features] = std_scaler.fit_transform(df[num_features])

In [15]:
df_std_scaled[num_features]

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
0,0.030671,-1.063611,1.134739,0.148453,-0.21666,-0.035429
1,0.837109,-1.008707,1.134739,-0.145920,-0.21666,-2.222153
2,-0.042642,0.245079,-0.420060,-0.145920,-0.21666,-0.035429
3,1.057047,0.425801,-1.197459,-0.145920,-0.21666,-0.035429
4,-0.775768,1.408176,1.134739,-0.145920,-0.21666,-0.035429
...,...,...,...,...,...,...
32556,-0.849080,0.639741,0.746039,-0.145920,-0.21666,-0.197409
32557,0.103983,-0.335433,-0.420060,-0.145920,-0.21666,-0.035429
32558,1.423610,-0.358777,-0.420060,-0.145920,-0.21666,-0.035429
32559,-1.215643,0.110960,-0.420060,-0.145920,-0.21666,-1.655225
32560,0.983734,0.929893,-0.420060,1.888424,-0.21666,-0.035429

In [16]:
# b. Min-Max Scaling
from sklearn.preprocessing import MinMaxScaler

In [17]:
mm_scaler = MinMaxScaler()
df_mm_scaled = df.copy()
df_mm_scaled[num_features] = mm_scaler.fit_transform(df[num_features])

In [18]:
df_mm_scaled[num_features]

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
0,0.301370,0.044302,0.800000,0.021740,0.0,0.397959
1,0.452055,0.048238,0.800000,0.000000,0.0,0.122449
2,0.287671,0.138113,0.533333,0.000000,0.0,0.397959
3,0.493151,0.151068,0.400000,0.000000,0.0,0.397959
4,0.150685,0.221488,0.800000,0.000000,0.0,0.397959
...,...,...,...,...,...,...
32556,0.136986,0.166404,0.733333,0.000000,0.0,0.377551
32557,0.315068,0.096500,0.533333,0.000000,0.0,0.397959
32558,0.561644,0.094827,0.533333,0.000000,0.0,0.397959
32559,0.068493,0.128499,0.533333,0.000000,0.0,0.193878
32560,0.479452,0.187203,0.533333,0.150242,0.0,0.397959

●	Discuss the scenarios where each scaling technique is preferred and why.

Standard Scaling:Also called Z -score scaling
Most commonly used scaling technique.
Used for Algorithms assuming normal distribution (Logistic Regression, SVM, PCA)

Min-Max Scaling: Best for Distance-based models (KNN, Neural Networks) and bounded features.

2. Encoding Techniques:

●	Apply One-Hot Encoding to categorical variables with less than 5 categories.

In [22]:
from sklearn.preprocessing import OneHotEncoder

In [24]:
one_hot=OneHotEncoder()

In [23]:
# Select columns with less than 5 unique categorie
low_cat = [col for col in categorical_cols if df[col].nunique() <= 5]
low_cat

['race', 'sex', 'income']

In [25]:
# applying onehotencoder and converting to dataframe
df1=pd.DataFrame(one_hot.fit_transform(df[['sex']]).toarray(),columns=['Female','Male'])
df2=pd.DataFrame(one_hot.fit_transform(df[['race']]).toarray(),columns=['White','Black','Asian-Pac-Islander', 'Amer-Indian-Eskimo', 'Other'])
df3=pd.DataFrame(one_hot.fit_transform(df[['income']]).toarray(),columns=['<=50K','>50K'])

In [26]:
df_final = pd.concat([df, df1, df2, df3], axis=1)

# Drop original categorical columns
df_final.drop(columns=['sex', 'race', 'income'], inplace=True)

df_final.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,capital_gain,capital_loss,...,native_country,Female,Male,White,Black,Asian-Pac-Islander,Amer-Indian-Eskimo,Other,<=50K,>50K
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,2174,0,...,United-States,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,0,0,...,United-States,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,0,0,...,United-States,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,0,0,...,United-States,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,0,0,...,Cuba,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [56]:
df_final = pd.concat([df, df1, df2, df3], axis=1)

# Drop original categorical columns
df_final.drop(columns=['sex', 'race', 'income'], inplace=True)

df_final.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,capital_gain,capital_loss,...,native_country,Female,Male,White,Black,Asian-Pac-Islander,Amer-Indian-Eskimo,Other,<=50K,>50K
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,2174,0,...,United-States,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,0,0,...,United-States,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,0,0,...,United-States,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,0,0,...,United-States,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,0,0,...,Cuba,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

●	Use Label Encoding for categorical variables.

In [27]:
from sklearn.preprocessing import LabelEncoder
high_cat = [col for col in categorical_cols if df[col].nunique() > 5]
high_cat

['workclass',
 'education',
 'marital_status',
 'occupation',
 'relationship',
 'native_country']

In [28]:
# appling label encoder
le = LabelEncoder()
for col in high_cat:
    df_final[col] = le.fit_transform(df_final[col])

In [60]:
df_final.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,capital_gain,capital_loss,...,native_country,Female,Male,White,Black,Asian-Pac-Islander,Amer-Indian-Eskimo,Other,<=50K,>50K
0,39,6,77516,9,13,4,0,1,2174,0,...,38,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,50,5,83311,9,13,2,3,0,0,0,...,38,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,38,3,215646,11,9,0,5,1,0,0,...,38,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,53,3,234721,1,7,2,5,0,0,0,...,38,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,28,3,338409,9,13,2,9,5,0,0,...,4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

Feature Engineering:

●Create at least 2 new features that could be beneficial for the model. Explain the rationale behind your choices.

In [35]:
df_final['capital_net'] = df_final['capital_gain'] - df_final['capital_loss']
df_final["work_intensity"] = df_final["hours_per_week"] * df_final["age"]
df_final

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,capital_gain,capital_loss,...,Male,White,Black,Asian-Pac-Islander,Amer-Indian-Eskimo,Other,<=50K,>50K,capital_net,work_intensity
0,39,6,77516,9,13,4,0,1,2174,0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,2174,1560
1,50,5,83311,9,13,2,3,0,0,0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0,650
2,38,3,215646,11,9,0,5,1,0,0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0,1520
3,53,3,234721,1,7,2,5,0,0,0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0,2120
4,28,3,338409,9,13,2,9,5,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0,1120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,3,257302,7,12,2,12,5,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0,1026
32557,40,3,154374,11,9,2,6,0,0,0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0,1600
32558,58,3,151910,11,9,6,0,4,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0,2320
32559,22,3,201490,11,9,4,0,3,0,0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0,440
32560,52,4,287927,11,9,2,3,5,15024,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,15024,2080

1.Feature 1: Capital Net (Wealth Indicator)
capital-gain and capital-loss individually represent income from investments

Combining them gives a net wealth indicator

2.Feature 2: Work Intensity (Age × Effort)
Income is influenced by both (age) and working hours

This feature captures their combined effect

●	Apply a transformation (e.g., log transformation) to at least one skewed numerical feature and justify your choice.

In [44]:
df.skew(numeric_only=True) ## checking for skewness

age                0.558743
fnlwgt             1.446980
education_num     -0.311676
capital_gain      11.953848
capital_loss       4.594629
hours_per_week     0.227643
capital_net       11.871934
dtype: float64

In [45]:
df_final["capital_gain_log"] = np.log1p(df["capital_gain"]) # capital_gain is highly right skewed
df_final["capital_gain_log"].skew()

np.float64(3.096143524467517)

Justification: as capital_gain is higly right skewed
so we have applied log tranformation as it:
Reduces skewness
Improves model stability