Section A: Data Structures & Control Structures

In [ ]:
# 1.Create a list of 5 integers. 
#Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
List1=[10,20,15,25,55,60,80] ### creation of a list
print(List1)

[10, 20, 15, 25, 55, 60, 80]

In [2]:
List1.append(100) ### adds element at the end of the list
print("After append :",List1)

After append : [10, 20, 15, 25, 55, 60, 80, 100]

In [3]:
List1.extend([70,80,90])### adds multiple elements to the end of an existing list
print("After extend:",List1)

After extend: [10, 20, 15, 25, 55, 60, 80, 100, 70, 80, 90]

In [4]:
List1.insert(4,30)### inserts element at a given index position 
print("After insert(30 at index 4):",List1)

After insert(30 at index 4): [10, 20, 15, 25, 30, 55, 60, 80, 100, 70, 80, 90]

In [5]:
List1.remove(100)### delets the given element from the list
print("After remove(100):",List1)

After remove(100): [10, 20, 15, 25, 30, 55, 60, 80, 70, 80, 90]

In [6]:
List1.pop()### delets the last element of the given list
print("After pop:",List1)

After pop: [10, 20, 15, 25, 30, 55, 60, 80, 70, 80]

In [7]:
index_of_55=List1.index(55)## gives index position of given element
print("index of 55:",index_of_55)

index of 55: 5

In [8]:
Count_80=List1.count(80)### gives the number of times given element is present in the list
print("Count of 80:",Count_80)

Count of 80: 2

In [9]:
List1.sort()### sorts list in ascending order
print("After sort:",List1)

After sort: [10, 15, 20, 25, 30, 55, 60, 70, 80, 80]

In [10]:
List1.reverse()### reverses the order 
print("After reverse:",List1)

After reverse: [80, 80, 70, 60, 55, 30, 25, 20, 15, 10]

In [11]:
List1.clear()## deletes every item in the list
print("After clear:",List1)

After clear: []

In [ ]:
#2.	Create a tuple that stores 3 student names.
#Try changing the second name in the tuple. What happens? Explain why.

In [12]:
Tuple1=("Kiraan","Nishad","Ruhi")## ceation of tuple with 3 students names
print(Tuple1)

('Kiraan', 'Nishad', 'Ruhi')

In [13]:
# Try changing the second name
Tuple1[1]="Prachi"

TypeError: 'tuple' object does not support item assignment

In [ ]:
### Tuples are immutable.Once a tuple is created,its elements cannot be changed,added or removed.

In [ ]:
#3.   Create a set of integers with some duplicate values. Print the set and explain the output.

In [14]:
set1={1,2,5,3,3,4,4,8,6}
print("set1:",set1)

set1: {1, 2, 3, 4, 5, 6, 8}

In [ ]:
### A set in python stores unique elements only.
# When you create a set and include duplicate values (e.g 3,4) ,Python automatically removes the duplicates.
# Hence the output contains each number only once.
# Also set sorts the values in ascending order.

In [ ]:
# 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. 
#Update the age and add a new key 'email'. Print the final dictionary.

In [15]:
dict1={'name':["Kiraan","Ruhi"],
       'age':[32,17],
       'city':["Mumbai","Pune"]}
print(dict1)

{'name': ['Kiraan', 'Ruhi'], 'age': [32, 17], 'city': ['Mumbai', 'Pune']}

In [16]:
dict1['age'][1]=33 ## updating the age of index 1
dict1['email']="kiraan@gmail.com" ## adding new key email
print(dict1)

{'name': ['Kiraan', 'Ruhi'], 'age': [32, 33], 'city': ['Mumbai', 'Pune'], 'email': 'kiraan@gmail.com'}

In [ ]:
#5   Write a script that checks if a person is eligible to vote (age ≥ 18). 
#Take age as a variable and print the appropriate message.

In [17]:
age=20 # Taking age as a variable
#checking eligibility
if age>=18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")

You are eligible to vote.

In [ ]:
#6. 6.	Given a 'marks' variable, print the grade:
# 90 and above: 'A'
# 75–89: 'B'
# 50–74: 'C'
# Below 50: 'Fail'

In [18]:
marks=89 ## Taking marks as a variable
# checking grade 
if marks>=90:
    print("Grade:A")
elif marks>=75:
    print("Grade:B")
elif marks>=50:
    print("Grade:C")
else:
    print("Grade:Fail")

Grade:B

In [ ]:
# 7.	Given a number, check if it's positive, and if it is also even.
# If not positive, print if it's zero or negative.

In [19]:
num=4
if num>0:
    print("The number is positive")
    if num % 2==0:
      print("It is also even")
elif num==0:
  print("The number is zero")
else:
 print("The number is negative")

The number is positive
It is also even

Section B: Numpy

In [ ]:
# 8.	Create:
# A scalar using np.array(5)
# A 1D array with values 1 to 5
# A 2D array (2x3) with values from 10 to 60 in steps of 10

In [1]:
import numpy as np

In [2]:
## A scalar using np.array(5)
scalar=np.array(5)
print("Scalar:",scalar)

Scalar: 5

In [3]:
## A 1D array with values 1 to 5
One_dim=np.arange(1,6)
One_dim

array([1, 2, 3, 4, 5])

In [4]:
#A 2D array (2x3) with values from 10 to 60 in steps of 10
two_dim=np.arange(10,70,10).reshape(2,3)
two_dim

array([[10, 20, 30],
       [40, 50, 60]])

In [5]:
#9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().
two_dim1=np.random.randint(0,100,16).reshape(4,4)
two_dim1

array([[ 9, 13,  6, 41],
       [88, 72,  1, 70],
       [67, 67, 53, 39],
       [55, 24, 45, 24]], dtype=int32)

In [ ]:
#10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [7]:
import numpy as np
import pandas as pd
Two_dim=np.array([[1,2,3],[4,5,6],[7,8,9]]) # 2D numpy array of shape (3x3)
df=pd.DataFrame(Two_dim,columns=['A','B','C']) # Convert to pandas DataFrame with column names: 'A', 'B', 'C'.
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

Section C: Exploring Pandas

In [ ]:
#11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
# Use .info(), .describe()
# Select 'Name' and 'City' columns
# Drop 'City' column
# Fill any missing values in 'Salary' column with the mean
# Remove any duplicate rows

In [8]:
# Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'
import pandas as pd
import numpy as np
data={"Name":["Kiraan","Nishad","Prachi","Ruhi","Satej","Tejit","Bhaumi","Purvi","Kiaan","Ninad"],"Age":[32,35,42,37,38,33,28,45,41,29],
      "City":["Mumbai","Mumbai","Mumbai","Pune","Thane","Panvel","Pune","Palghar","Chennai","Bangalore"],
      "Salary":[50000,62000,55000,45000,46000,42000,43000,40000,35000,38000]}
df1=pd.DataFrame(data)
print(df1)

     Name  Age       City  Salary
0  Kiraan   32     Mumbai   50000
1  Nishad   35     Mumbai   62000
2  Prachi   42     Mumbai   55000
3    Ruhi   37       Pune   45000
4   Satej   38      Thane   46000
5   Tejit   33     Panvel   42000
6  Bhaumi   28       Pune   43000
7   Purvi   45    Palghar   40000
8   Kiaan   41    Chennai   35000
9   Ninad   29  Bangalore   38000

In [9]:
df1.info() # gives information such as column name,number of enteries,null/non-null count and datatype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

In [10]:
df1.describe() ## generates summary statistics for the numeric columns in dataframe

             Age        Salary
count  10.000000     10.000000
mean   36.000000  45600.000000
std     5.637178   8154.071921
min    28.000000  35000.000000
25%    32.250000  40500.000000
50%    36.000000  44000.000000
75%    40.250000  49000.000000
max    45.000000  62000.000000

In [11]:
df1[["Name","City"]]# Select 'Name' and 'City' columns

     Name       City
0  Kiraan     Mumbai
1  Nishad     Mumbai
2  Prachi     Mumbai
3    Ruhi       Pune
4   Satej      Thane
5   Tejit     Panvel
6  Bhaumi       Pune
7   Purvi    Palghar
8   Kiaan    Chennai
9   Ninad  Bangalore

In [12]:
# Drop 'City' column
df1_dropped=df1.drop(columns=["City"])
print(df1_dropped)

     Name  Age  Salary
0  Kiraan   32   50000
1  Nishad   35   62000
2  Prachi   42   55000
3    Ruhi   37   45000
4   Satej   38   46000
5   Tejit   33   42000
6  Bhaumi   28   43000
7   Purvi   45   40000
8   Kiaan   41   35000
9   Ninad   29   38000

In [13]:
# Fill any missing values in 'Salary' column with the mean
data1={"Name":["Kiraan","Nishad","Prachi","Ruhi","Satej","Tejit","Bhaumi","Purvi","Kiaan","Ninad"],"Age":[32,35,42,37,38,33,28,45,41,29],
      "City":["Mumbai","Mumbai","Mumbai","Pune","Thane","Panvel","Pune","Palghar","Chennai","Bangalore"],
      "Salary":[50000,62000,55000,45000,46000,42000,43000,np.nan,40000,38000]}
df2=pd.DataFrame(data1)
df2

     Name  Age       City   Salary
0  Kiraan   32     Mumbai  50000.0
1  Nishad   35     Mumbai  62000.0
2  Prachi   42     Mumbai  55000.0
3    Ruhi   37       Pune  45000.0
4   Satej   38      Thane  46000.0
5   Tejit   33     Panvel  42000.0
6  Bhaumi   28       Pune  43000.0
7   Purvi   45    Palghar      NaN
8   Kiaan   41    Chennai  40000.0
9   Ninad   29  Bangalore  38000.0

In [26]:
mean_Salary=df2['Salary'].mean()
df2.fillna({'Salary': mean_Salary}, inplace=True) ### replaces missing value with mean
(df2)

     Name  Age       City        Salary
0  Kiraan   32     Mumbai  50000.000000
1  Nishad   35     Mumbai  62000.000000
2  Prachi   42     Mumbai  55000.000000
3    Ruhi   37       Pune  45000.000000
4   Satej   38      Thane  46000.000000
5   Tejit   33     Panvel  42000.000000
6  Bhaumi   28       Pune  43000.000000
7   Purvi   45    Palghar  46777.777778
8   Kiaan   41    Chennai  40000.000000
9   Ninad   29  Bangalore  38000.000000

In [24]:
## Creating dataframe with duplicate row
data2={"Name":["Kiraan","Nishad","Prachi","Ruhi","Satej","Tejit","Bhaumi","Purvi","Purvi","Ninad"],"Age":[32,35,42,37,38,33,28,45,45,29],
      "City":["Mumbai","Mumbai","Mumbai","Pune","Thane","Panvel","Pune","Palghar","Palghar","Bangalore"],
      "Salary":[50000,62000,55000,45000,46000,42000,43000,40000,40000,38000]}
df3=pd.DataFrame(data2)
df3.duplicated().sum() ## checking duplicate values

np.int64(1)

In [25]:
df3

     Name  Age       City  Salary
0  Kiraan   32     Mumbai   50000
1  Nishad   35     Mumbai   62000
2  Prachi   42     Mumbai   55000
3    Ruhi   37       Pune   45000
4   Satej   38      Thane   46000
5   Tejit   33     Panvel   42000
6  Bhaumi   28       Pune   43000
7   Purvi   45    Palghar   40000
8   Purvi   45    Palghar   40000
9   Ninad   29  Bangalore   38000

In [22]:
df3_drop_duplicates = df3.drop_duplicates() ## dropping duplicates
df3_drop_duplicates

     Name  Age       City  Salary
0  Kiraan   32     Mumbai   50000
1  Nishad   35     Mumbai   62000
2  Prachi   42     Mumbai   55000
3    Ruhi   37       Pune   45000
4   Satej   38      Thane   46000
5   Tejit   33     Panvel   42000
6  Bhaumi   28       Pune   43000
7   Purvi   45    Palghar   40000
9   Ninad   29  Bangalore   38000