BASIC STATISTICS-2
Problem Statement : Hospital Patient Data Analysis

In [1]:
import pandas as pd

In [2]:
# 1.Loading datasets
patient_df=pd.read_csv("Patient_Data.csv")
billing_df=pd.read_csv("Billing_Data.csv")

In [4]:
# show summary with info()
patient_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [5]:
billing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         5 non-null      int64
 1   InsuranceCovered  5 non-null      int64
 2   FinalAmount       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [6]:
# 2.Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
patient_df[['PatientID', 'Department', 'Doctor', 'BillAmount']]

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [7]:
# 3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].
patient_df.drop(columns=['ReceptionistID', 'CheckInTime'],inplace =True)
patient_df

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [8]:
#4.	Use groupby to find total bill amount per department
patient_df.groupby('Department')['BillAmount'].sum()

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [9]:
#5.	Remove duplicate patient records based on PatientID.

In [9]:
# Checking for duplicates
patient_df.duplicated().sum()

np.int64(1)

In [10]:
# looking for duplicated value
patient_df[patient_df.duplicated()]

   PatientID   Name  Department     Doctor  BillAmount
5        101  Alice  Cardiology  Dr. Smith      5000.0

In [11]:
# removing duplicated value
patient_df.drop_duplicates(subset='PatientID',inplace=True)

In [12]:
# checking for ,duplicates value removed or not
patient_df.duplicated().sum()

np.int64(0)

In [29]:
# 6.	Fill missing BillAmount values with the mean bill amount.
mean_bill=patient_df['BillAmount'].mean()
patient_df.fillna({'BillAmount': mean_bill})
patient_df

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

In [31]:
#7.	Merge the billing dataset with patient dataset on PatientID.
merge_df=pd.merge(patient_df,billing_df,on='PatientID',how='left') # using leftmerge
merge_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [19]:
#8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

In [32]:
# Creation of an additional DataFrame 
new_patient={'PatientID':[106,107],'Name':['Raj','Sam'],'Department':['Cardiology','Orthopedics'],'Doctor':['Dr. Smith','Dr.Lee'],
             'BillAmount':[5000,7000]}
new_patient_df=pd.DataFrame(new_patient)
new_patient_df

   PatientID Name   Department     Doctor  BillAmount
0        106  Raj   Cardiology  Dr. Smith        5000
1        107  Sam  Orthopedics     Dr.Lee        7000

In [33]:
# Concatenate (row-wise,axis=0).
concate_df=pd.concat([patient_df,new_patient_df],ignore_index=True,axis=0)
concate_df

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333
5        106      Raj   Cardiology  Dr. Smith  5000.000000
6        107      Sam  Orthopedics     Dr.Lee  7000.000000

In [34]:
#9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).
new_billing={'InsuranceCovered':[2000,1000,1500,3000,4000,2500,3500],'FinalAmount':[3000,5233.33,6000,4700,2233.33,2500,3500]}
new_billing_df=pd.DataFrame(new_billing)
Final_bill_df=pd.concat([concate_df,new_billing_df],axis=1)
Final_bill_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000.00
1,102,Bob,Neurology,Dr. John,6233.333333,1000,5233.33
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,1500,6000.00
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,4700.00
4,105,Eva,Dermatology,Dr. Rose,6233.333333,4000,2233.33
5,106,Raj,Cardiology,Dr. Smith,5000.000000,2500,2500.00
6,107,Sam,Orthopedics,Dr.Lee,7000.000000,3500,3500.00

In [35]:
# Doctor wise Final Amount
Final_bill_df.groupby('Doctor')['FinalAmount'].sum()

Doctor
Dr. John      5233.33
Dr. Lee       6000.00
Dr. Rose      2233.33
Dr. Smith    10200.00
Dr.Lee        3500.00
Name: FinalAmount, dtype: float64